FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ./TFG_Web/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1


WORKDIR /app
COPY --from=build-env /app/out .
RUN apt-get update -qq && apt-get -y install libgdiplus libc6-dev

ENTRYPOINT ["dotnet", "TFG_Web.dll"]
